version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v19.2.2
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    image: heroiclabs/nakama:3.3.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100 --console.username admin --console.password test123456
          --socket.server_key "mynewkey" --session.encryption_key "mynewkey" --runtime.http_key "mynewkey" --iap.google.client_email "rhythm@pc-api-8963274138522838975-447.iam.gserviceaccount.com"
          --iap.google.private_key "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQC4QGFCeBUm8Jfg\nG7xYVDqyQxfNFqL4DoE59viNHkTnVYLMdYQUZSjez3uEmoqtFOl4aW5vwlE/HXu/\nyKWO6uNELKXKbw6VILA7hR0LNW6C97N3gdd4uz6Y0fv5Ae0psWaVtne+DTfDdP8l\naRQXpE8MFX99DQBokB1c/Y3FSCLrQKZ9cMasNEPq5YVCs/9iPXWiE7Ao/WEb2HdD\nmNI/aqHa7MI1mtXPy1fLXRPfn+dnRd9GRtPaeKL9YVMoVKFXJucaOrlHmOD3/o4Q\noI1c6tk3g0gbt+pKXnSd99YWmzjYKMj29E8eQFpoqiSbO6e8G89Hx6KxSV92wwvq\npnCiYioLAgMBAAECggEAThb7IbDDRj2yIMmgic8pEWReMg3mBDwhiO+jaCvsCB+1\nz/H+iKZXLBfDwe+91p2GVgJZTASParCUQjRH9sqWh85kdeebxpiUGKXSKW376IYT\nChN9vy2c2iglIuQuH/2P/OPY3DO97pknijN+0IZS+kwiPF3GTorF5yOPco2gPxPv\nB3OgpTFiOsB+eMgNz0CHgBxsOdJSlDL44BMqmrzLtSUiaYsPNS3jH4OB4n2ARIsH\nf6Hr8rFmh+5mdfdmvSjJAQgyXZ31IPX5ltkW8DxkdyCV+TS+CXXaJSVZMccUAK9R\nR3XPEUJ8rG4jgPM83GbMd85cznLH5w5UL1QYYs2UAQKBgQDnMTB1n2SgdGo0aSMe\no4DCldLwW9ChJXAw3UWFnDGPLaEVlUMyI3nA3BvI5aZNlUDv4WDtHbbgG9a3MiW5\nkYrJu5cIaSrT2ihvOmc0FnUToU32KCzcte1EvCgbQrLtjY0Fr5j7LFougW1BLoNf\nP1PZmN2zbu9Q+uxewe0mGspf/QKBgQDMBbz/a5zXjcGSYvGN8xpHGOYXfGCLHBt4\n88f+Wk6LI2hcRRWkQsKeerI9Dzc3S206zFT7yEiba/dOWsY8OkJmIIufahOhLouN\nnNXUeGuNqjePDyr8fYyVFudW7ZBZ92hHfiYIYKGefnAPOvY9IssfSAfT3Cl7Xrr/\nK+RHqgt8pwKBgQC8Rzbr048jjSsg266aORWXYmSTEnLpiY/Ae7MuiHFj5QkWhqRe\npL127spB5aR18mMb+DPzZwuTn5hRQSmv4nNgrsDlPKCAP15Glw2NQey+u9K98SH3\n7MD6BTG0YbFN/MUoKEUx6IDY9tZ/Ct46J1ymDPQgOOv0yyTMVqpHKfI+EQKBgHYG\nx8xXW9eTKS1fUfBVd5kzvUBO8qbnLrltBgCOC6wQYromORvahy4ZOu151O6HEvyV\n4n/54I8RCXNprg5/gZQFNeCWBB8VhyP4W/dbZpUAqL14/9wrYV2Kb3BpZD23k7rw\nLl5gUH8ZFAirinHZo/pHuEeGsPSu26zsnlYa+CQ3AoGBAM7kvovfD3uaX6tKCbtm\n9dPdxImzl5FpA+QWnO2pzjmhQeInJsTFOVXjFYYKSWT4yCVn0lJbqsSCwxI3LQ/A\nKIFs4Jdw3afpr845PxrS3AEycLa3YD1yKzMbNLP7OzI3sf8ixsyhIC0RFdBtgEda\nWB89leQOwVz5Lrg/UHVqv09W\n-----END PRIVATE KEY-----\n"
    restart: always
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
      - prometheus
    volumes:
      - ./nakama/data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']

        - job_name: nakama
          metrics_path: /
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - '9090:9090'

volumes:
  data:
