version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v19.2.2
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    image: heroiclabs/nakama:3.3.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100 --console.username admin --console.password test123456
          --socket.server_key "mynewkey" --session.encryption_key "mynewkey" --runtime.http_key "mynewkey" --iap.google.client_email "rhythm@pc-api-8963274138522838975-447.iam.gserviceaccount.com"
          --iap.google.private_key "-----BEGIN PRIVATE KEY-----\nMIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCl/bX0E7oJksRW\n0t/qKXQJfg7BGwEwniFAxl/w15+USKw3ddNCuFeRfZrh0BD0M7zerV2jwQEBDzwg\nmoYhQQYw7u17xxd0MWwgax2G83rrrL+3xW5XATFit+JPltQtVwKnMUaBuFdOMwb8\nAbISjdbzeBmQJCBeJ4owV2qZdDMQ+iAb6qntVbRmsm4NFQjC7TuV5Wcd/CpCUqk5\nOtLBQCFjvxJ8LB33FKZd+cfC8kXMPtqgncSMXjldzOgw+vfCOBpcIUd7Rm/PIeK3\nqbm5fc4BQ+QtztThvmZ5PMbzoeL7YleKUT2DYhkh4FG+k442wGIFbn/djnlE9E7O\ngUPByDExAgMBAAECggEAAIR8/RN+q1ROJmh76D1ULkoP/mF41yT3Ej5MGEfOfeYy\nxe1+c3Z4V2zJKdZokcpY1rzlo4K7imb4wgVD+8s5xgyd/Zp4+T9viIkCS48WHVv+\n27IoOOnjtIdsPjad12euYMUSOjSlQ7TRsGwfmQKLiVt2K5vhOfSXmrT7ERq/+gKR\nrWblMuUmSX4GNj+XtSqFAjOxZ2OQpn3otZr9j2Lq8f00k2TthllVenH//7ueTa1u\n65rkH4lv9CAIkS5yaWMUW87vBdyyywukE/BRvydny/2AWJ93ZW7p6JkfwY/n6BsV\nVdYc+6r7HQzm0nPXh/3ZcHJ91tuYNaA8rYzjn+2AkQKBgQDg7COWPgHLJK+Aup+p\nrERZfJwQXpilgw7QMmScAXYFUuuet6JTVYKhG+z+/S9O6XxjHvDeYTLO3Av2jsjS\nxY4RrLWUFVVd3G2+FdEvDLtOxhHvJyqrGs7VO71aqjgnx7HabQUDMY725F60/BsI\nUCl8hTIXmoAxfpVXXdOq0ICoJQKBgQC87ROVaLtAkjjAtoOgHyUdVPZPILuWN0GB\n72iXKhngdok+ZYaNT+Ts5Sg1RTJsSJIcAAhHxdJEN28PA+al0kl3E7NTLypMUWB3\nAxImRWrb3UZqo3uhV3YHnsMNC5yCzw5RXXd3+9cqjauIsBlTk9eBUYymDKO0FFLk\nfwB78EkBHQKBgQDMRaoMSURXunmp79QRxOJOY11ZgJAhwWUysJGvHaSSMTzMaPqD\ntKVurG4RJuBQSr0tSGx5is0aEb7LreG1irX8V16Rns5o8Ei62hWhJW73m+utx2R5\nAV/XSOov7WgSuMpOFbT3sYqlr8JTnKLwad1DubREu4yxZsU7E3upJrOyAQKBgFhF\nuTm9FojECUpZvMRq6O98jB1KoPs91Bi+4LKIlFChcdy6mRSbuM3LAG9rZnTbr5Dv\nnu7SCj2fXP+6BeGCkJrXlJkQV4YTG6xfvfItyxDxoX4f5prq/5Xt4xrMSxN/ZSQ1\nNKXWAKG8UeJqzVqUoEOm8719+Fsih9yFTpeaHLItAoGAGI4URnviQrU14r96GVBP\nZ014Fu+24n5urDbCDV3X/Ti0mkLd+ds22T6fANIYA2QyaQEWum1E9K+eojSAOjQ3\nzAcPeQzy+yzrKqQPPOQi/0lzO59WV914D+T3ivB3EdSrYMuAjic7icKZY2N+n1V2\nGad85r+SwQkhLMgvAw6RZS0=\n-----END PRIVATE KEY-----\n"
    restart: always
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
      - prometheus
    volumes:
      - ./nakama/data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']

        - job_name: nakama
          metrics_path: /
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - '9090:9090'

volumes:
  data:
