version: '3'
services:
  cockroachdb:
    image: cockroachdb/cockroach:v19.2.2
    command: start --insecure --store=attrs=ssd,path=/var/lib/cockroach/
    restart: "no"
    volumes:
      - data:/var/lib/cockroach
    expose:
      - "8080"
      - "26257"
    ports:
      - "26257:26257"
      - "8080:8080"
  nakama:
    image: heroiclabs/nakama:3.3.0
    entrypoint:
      - "/bin/sh"
      - "-ecx"
      - >
          /nakama/nakama migrate up --database.address root@cockroachdb:26257 &&
          exec /nakama/nakama --name nakama1 --database.address root@cockroachdb:26257 --logger.level DEBUG --session.token_expiry_sec 7200 --metrics.prometheus_port 9100 --console.username admin --console.password test123456
          --socket.server_key "mynewkey" --session.encryption_key "mynewkey" --runtime.http_key "mynewkey" --iap.google.client_email "nakama@pc-api-8963274138522838975-447.iam.gserviceaccount.com"
          --iap.google.private_key "-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCwfVLCKfRMapzd\nEayV2QSqdtURLND83aBcXiBvt/8+O1zFosjpyWbiEPySV9hsOffP3JeyI55Y4scx\nXI7JEAwBDbKUxyyHQjXuSkOxRRmBR8eXCEvwjd9csN4ztZP1I2obyuon23NiHR98\nBu+OZF320kj10x7Xa5ZGKeX7V+ZAeG6iQzJV2IVIpqDJ9TGYTfpjrQU1wJK5tx4Y\ndBNk9TPbySMCYFKyxvqInSsNxqG8sbtRi6iQpnX1h4FfDYgM+zzZX1j9jxdoE5+T\nfWmxaaLQni0ukJDzKcmEUeRWP4YlwuQ3lH9tJmWeMt01Lst9K9V1nOwAMo1phoxQ\nz4E+EV3lAgMBAAECggEAAosj1LGHGEzXCuaUzqoMg6pnwrIbJvHIvFwM6p9DufFg\nEmcYryncZjipczB56YFiXWgH9aTGxPArv73ePu6QxbkdUECYlzBwl4kRda4Rwoe2\nzCnt8j8RL4RLB4K/6aIDhvgDLOTgQlM6H274J9yxb/uy2nwa7y7ZQRScgGVRZ69u\nhCJKXxOjXCkNpgsky+fyLvR3xJCKQFoV2ZlKaj+ItPA2Mn1M+how26UEDnptjDH6\n+w43j86L5I9mKsUlhG4r3KuylvBGo5BHI9b5wZ/dSXFsUyCit7NAKO1fobmIPnzw\nMtx357f6xzAx+uWeVu/BitPiO4wy+IoOUF0vjeEIxwKBgQDXnZWFQddR7LvNErdt\nqAiICpzibKLcZZgWq3n7O/w8GB1RufXcAphu5A3pzUQ8PbJYaOfz7AvdMuVAK+dn\nUK9Z6JWD4vQ+NdB8bY3cOwyXa3Dzro6MMCCv/vVh4ajCIQfG4EpqD7GLauTXnNsI\nCYZOSDtyliTXvuEID+A0Jp6ijwKBgQDRi7XOUR9NtG+wluhuI9bWQQjkko2ROZpv\nL2l9P55Q8efzyUwdrUpWkCFK4ChnOXeuhRz3LXODLvjKkptGqSMD6kRopl0qSBqP\nq0Hsb4395S//e66UUtUY7j7zLsA+Y4vnDR0nVrYsr/3iEDypJUoOil5XSA5h2Yeb\nLbDZEVNiSwKBgE8/xG0uPg4GjSBa+MB9OmWGQROYCmQnkzcB39vPuG3+Dwiy6QLs\nkUpw2AxPPf1GT/7e0CJ/Z/ztcAWeHXeD2G+bZRkMmekjrnWNbs67hW1COEnYptwv\n9FO7ykUnw/dWXJ1kYvWIvyEXMPVu2bKijZLISdFcDj6eEef8rdN9PmFRAoGBAJcX\nbP0aAz9NRmeHOIsKLoOImzfs8ETxywg2oJKeB7KH6t8em1KevAZUoJzTqm5bwo9F\nDhCwZiUF/oBaW7oEhOnyxmbK5kxxdy12p+8qtLCIzCYkcUoju+HhD+TbJeUWdC8i\nho3x+SOZtq+FU6gG6jI31TSMEUq+xge/V0/9LSmnAoGBAJ3JGn2vdSBoBBF0LtVw\nAhZTIjklkKNuzQd840p8IyqioqBbsX7OLW0YfZSTucdvy+j3/2GKuqYXTTv5TaYb\nQwMhdsCFH/Tq6HpYz0tAbSfVUry4AORPonrHKJeK+Z3OLfcgtysIcvzbn6qKnVRH\nKT+wGoS5pCA0SlgostKWwHkt\n-----END PRIVATE KEY-----\n"
    restart: always
    links:
      - "cockroachdb:db"
    depends_on:
      - cockroachdb
      - prometheus
    volumes:
      - ./nakama/data:/nakama/data
    expose:
      - "7349"
      - "7350"
      - "7351"
      - "9100"
    ports:
      - "7349:7349"
      - "7350:7350"
      - "7351:7351"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7350/"]
      interval: 10s
      timeout: 5s
      retries: 5
  prometheus:
    image: prom/prometheus
    entrypoint: /bin/sh -c
    command: |
      'sh -s <<EOF
        cat > ./prometheus.yml <<EON
      global:
        scrape_interval:     15s
        evaluation_interval: 15s

      scrape_configs:
        - job_name: prometheus
          static_configs:
          - targets: ['localhost:9090']

        - job_name: nakama
          metrics_path: /
          static_configs:
          - targets: ['nakama:9100']
      EON
      prometheus --config.file=./prometheus.yml
      EOF'
    ports:
      - '9090:9090'

volumes:
  data:
